# HW1 解聯立方程式
http://www.math-exercises.com/equations-and-inequalities/linear-equations-and-inequalities

In [1]:
# 2i
from sympy.solvers import solve
from sympy import Symbol

x = Symbol('x')
solve([(x+2)*(x-3)-(x-5)*(x-6)], dict=True)

[{x: 18/5}]

In [2]:
# 2i
from sympy.solvers import solve
from sympy.core import sympify

exp1 = '(x+2)*(x-3), (x-5)*(x-6)'
solve(sympify(f"Eq({exp1})"))

[18/5]

In [5]:
# 3c
# 需加 real=True
x = Symbol('x', real=True)
solve(abs(10-2*x)-6, x,dict=True)

[{x: 2}, {x: 8}]

In [6]:
# http://www.math-exercises.com/equations-and-inequalities/systems-of-linear-equations-and-inequalities

In [8]:
from sympy import symbols
x,y,z = symbols('x,y,z')

In [9]:
5*x + 3*y + 1*z +2

5*x + 3*y + z + 2

$\displaystyle 4 x + 3 y = 4$

$\displaystyle 2 x + 2 y - 2 z = 0$

$\displaystyle 5 x + 3 y + z = -2$

# Lab 2
http://www.math-exercises.com/equations-and-inequalities/systems-of-linear-equations-and-inequalities

In [10]:
#3c
from sympy import symbols
x, y, z = symbols('x y z')
solve([4*x + 3*y -4, 2*x + 2*y - 2*z, 5*x + 3*y + 1*z +2], dict=True)


[{x: -11, y: 16, z: 5}]

In [1]:
# 3c
import numpy as np
def solve_equation(a, b):
    a_shape = int(len(a) ** .5)
    # TBD：檢查 a_shape 是否為整數?
    a=np.array(a).reshape(a_shape, a_shape)
    b=np.array(b)
    return np.linalg.solve(a,b)

solve_equation([4, 3, 0, 2, 2, -2, 5, 3, 1], [4, 0, -2])

array([-11.,  16.,   5.])

In [4]:
# 1a
solve_equation([1,1,1,-1], [5, 1])

array([3., 2.])

In [12]:
# 4a
solve_equation([2, 2, -1, 1, 4, 3, -1, 2, 8, 5, -3,  4, 3, 3, -2, 2], [4, 6, 12, 6])

array([ 1.,  1., -1., -1.])

In [4]:
# 3b
solve_equation([1, 1, 0, 0, 1, -1, 1, 0, -1], [13, 5, 2])

array([5., 8., 3.])

In [6]:
from sympy.solvers import solve

equations=[]
while True:
    x = input('請輸入方程式：')
    if x == '':
        break
    equations.append(x)
    
if len(equations)>0:
    for i in range(len(equations)):
        arr = equations[i].split('=')
        if len(arr) == 2:
            equations[i] = arr[0] + '-(' + arr[1] + ')'
    print(solve(equations))

請輸入方程式：x+y=13
請輸入方程式：y-z=5
請輸入方程式：x-z=2
請輸入方程式：
{x: 5, y: 8, z: 3}


In [1]:
import tkinter as tk
root = tk.Tk()
root.geometry("400x240")

def getTextInput():
    result=textExample.get("1.0","end")
    print(result)

textExample=tk.Text(root, height=10)
textExample.pack()
btnRead=tk.Button(root, height=1, width=10, text="Read", 
                    command=getTextInput)

btnRead.pack()

root.mainloop()

In [1]:
from sympy.solvers import solve
from tkinter import *

# 啟動視窗系統
root = Tk()

def run():
    equations_clean=[]
    expr1 = text1.get("1.0","end")
    equations = expr1.split('\n')
    if len(equations)>0:
        for i in range(len(equations)):
            if equations[i] == '':
                continue
#             print(equations[i])
            arr = equations[i].split('=')
            if len(arr) == 2:
                equations[i] = arr[0] + '-(' + arr[1] + ')'
            equations_clean.append(equations[i])
        print(equations_clean)
        answer1.set(solve(equations_clean))        

# 畫面設計
answer1 = StringVar() 
Label(root, text="請輸入方程式：(2x 需輸入 2*x)", height=1, font='Helvetic 18 bold').pack(fill=X)
text1 = Text(root, height=5, width=30, font='Helvetic 18 bold')
text1.pack()
Button(root, text="求解", font='Helvetic 36 bold', command=run).pack(fill=X)
Label(root, text="", height=1, font='Helvetic 18 bold', textvariable=answer1).pack(fill=X)


# 監聽事件
root.mainloop()


['x+y-(5)', 'x-y-(1)']
